version: '3.8'

services:
  mysql:
    image: mysql:8.0 # 使用 mysql 8.0 的版本, 啟動時會自動下載
    environment: # 抓取.env 環境變數
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}   # root 用戶的密碼, 直接設置即可, 登入時使用, 若不需要密碼 MYSQL_ALLOW_EMPTY_PASSWORD 設置為 true
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"            # 允許密碼為空
      MYSQL_DATABASE: ${DB_DATABASE}             # 預設要創建的資料庫名稱
    ports:
      - "3306:3306"
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
  redis:
    image: redis:7.4.1
    ports:
      - "6379:6379"